apiVersion: v1
kind: Service
metadata:
  name: nginxsvc
spec:
   type: NodePort
   selector:
       name: nginx
   ports:
      - name: nginx
        port: 80
        targetPort: 80
        nodePort: 31000
        