- name: install lamp and apache 
  hosts: webserver
  become: yes
  tasks:
     - name: install  apache2
       ansible.builtin.apt:
         name: "{{ package }}"
         update_cache: yes
         state: present
     - name: enable apache
       service:
          name: "{{ package }}"
          enabled : true
          state: started
     - name: install php
       ansible.builtin.apt:
          name: "{{ php_package }}"
          update_cache: yes
          state: present
     - name: restart apache2
       service:
          name: "{{ package }}"
          state: started
     - name: copy php.info
       copy:
         src: php.info
         dest: /var/www/html/info.php
     - name: restart apache2
       service: 
          name: "{{ package }}"
          state: started

           
       
