- name: install lamp and apache 
  hosts: webserver
  become: yes
  tasks:
     - name: fail for unsupported os
       ansible.builtin.fail:
         msg: "This playbook is designed only for Ubuntu os"
       when: ansible_facts['distribution'] == 'Ubuntu'
     - name: install  apache2
       ansible.builtin.apt:
         name: "{{ package }}"
         update_cache: yes
         state: present
     - name: enable apache
       service:
          name: "{{ package }}"
          enabled : true
          state: started
     - name: install php
       ansible.builtin.apt:
          name: "{{ php_packages }}"
          update_cache: yes
          state: present
     - name: restart apache2
       service:
          name: "{{ package }}"
          state: started
     - name: copy php.info
       copy:
         src: php.info
         dest: /var/www/html/info.php
     - name: restart apache2
       service: 
          name: "{{ package }}"
          state: started

           
       
