apiVersion: apps/v1
kind: Deployment
metadata:
   name: rabbitmq
spec:
  minReadySeconds: 5
  replicas: 1
  selector: 
     matchLabels: 
        app: rabbitmq
  strategy: 
     type:  RollingUpdate
     rollingUpdate: 
        maxSurge: 50%
        maxUnavailable: 50%
  template: 
     metadata: 
       name: rabbitmq
     spec: 
       containers:
         - name: workshop
           image: rabbitmq:3-management-alpine
           ports: 
             - name: rabbitmq
               containerPort: 15672
           resources: 
               limits:
                 cpu: "1000m"
                 memory: "500m"
           volumeMounts:
              - name: rabbitmqdata
                mountPath: /var/lib/rabbitmq
              - name:  ./rabbitmq
                mountPath: /etc/pitstop/"
           env:
             - name: RABBITMQ_CONFIG_FILE
               value: /etc/pitstop/rabbitmq.conf

---
apiVersion: v1 
kind: Service
metadata:
   name: rabbitmq
spec:
  selector: 
      app: rabbitmq
  ports:
    - name: rabbitmq
      protocol: TCP
      port: 15672
    - name: rabbitmq2
      protocol: TCP
      port: 5672

---
apiVersion: v1 
kind: PersistentVolumeClaim
metadata:
   name: pvc 
spec:
  accessModes: 
     - ReadWriteOnce
    

   




          
               
               

         
     