apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat
spec:
  minReadySeconds: 5
  replicas: 2
  selector: 
    matchLabels:
      name: tomcat
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 50%
      maxUnavailable: 50%
  template:
    metadata:
      labels:             # Change from "name: tomcat" to "name: tomcat"
        name: tomcat     # This ensures the label selector matches the Pod labels
    spec:
      containers:
        - name: tomcat
          image: tomcat:11.0
          ports:
            - name: tomcat
              containerPort: 8080
          resources:
            limits:
              cpu: "500m"
              memory: "250Mi"   # Corrected typo: "250mMi" -> "250Mi"
                
---

apiVersion: v1
kind: Service
metadata:
  name: tomcat
spec: 
  type: LoadBalancer
  selector:
    name: tomcat         # Match the label selector used by the Deployment
  ports:
    - name: tomcat
      port: 8080
      nodePort: 30007
      targetPort: 8080
