---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: http
  labels: 
   app: http
spec:
  minReadySeconds: 3
  replicas: 3
  selector:  
    matchLabels:
      app: http
  template: 
    metadata: 
      name: http
      labels: 
         env: dev
         app: http
         version: v1.3.0
    spec:
      containers:
       - name: http
         image: httpd:2
         ports: 
          containerPort: 8080   
---
apiVersion: v1
kind: Service
metadata:
  name: http
spec:
  type: NodePort
  port: 
    nodePort: 32000
    port: 8080
    targetport: 8080
