apiVersion: v1
kind: pod 
metadata:
  name: sql-pod
spec:
  containers:
    - name: mysql-pod
      image: mysql:8.0-debian
      env:
       - name: MYSQL_ROOT_PASSWORD
         value: nop@123
       - name: MYSQL_DATABASE
         value: nop
       - name: MYSQL_USER
         value: nop
       - name: MYSQL_PASSWORD
         value: nop@123