apiVersion: v1
kind: pod
metadata:
 name: nginx
spec:
 minReadySeconds: 10
 replicas: 3
 selector: 
  app: nginx
 template:
  metadata:
   labels:
    env: dev
    app: nginx
    version: "1.25"
  spec: 
    containers:
     - name: nginx
       image: nginx
       restartPolicy: Always
       resources:
        limits:
         cpu: "500m"
         memory: "250Mi"