apiVersion: apps/v1
kind: ReplicaSet
metadata:
 name: alpine-pod
 labels: 
   app: alpine
spec:
 minReadySeconds: 5
 replicas: 3
 selector:
  matchLabels:
    app: alpine-pod
 template:
  metadata:
   name: alpine-pod
   labels:
    app: alpine-pod
    env: dev
  spec:
   containers:
    - name: alpine-pod
      image: alpine:3.19
      resources:
       limits:
        cpu: "500m"
        memory: "250Mi"

